### ISSUE TITLE
Active Storage Error

### ISSUE THREAD

**Issue by kinmt1234** [cloudinary/cloudinary_gem#366]
Hi, first of all. Thanks for the amazing gem.
I am using `rails 6` and `ruby-2.6.4` the production server is `heroku`. I am trying to integrate cloudinary with activestorage but getting the following errors:
`ActiveStorage::IntegrityError (Unsupported source URL: #<StringIO:0x000056083b6e0ea8>)`
Any helps?

**Comment by aleksandar-cloudinary** [comment]
Hi @kinmt1234 Glad you like the gem. In terms of the error; may I please ask you to share the upload source (i.e. file, base64 data uri, s3/gs URL etc) that lead to this error?

**Comment by kinmt1234** [comment]
@aleksandar-cloudinary  sure, I am using one of js plugins.

`decoded_data = Base64.decode64(data)`
`washed_image = MiniMagick::Image.read(decoded_data)`
`washed_image.format("png")`
`object.images.attach(`
` io: StringIO.new(washed_image.to_blob),`
`filename: "image.png",`
`content_type: "image/jpeg"`
` )`

**Comment by aleksandar-cloudinary** [comment]
Thanks for providing this @kinmt1234. Could you please try to pass 'washed_image.to_blob' to io: directly rather than as a StringIO object? Also, is there any reason the format is set to PNG but the content_type is for a JPG?

**Comment by matedemorphy** [comment]
@kinmt1234  i'm getting this error:

undefined method `read' for #<String:0x00007f7b3400e720>

**Comment by aleksandar-cloudinary** [comment]
Hi @matedemorphy. What version of the gem are you running? In addition, what is the value of the String you're passing to the upload method?

**Comment by NickNish09** [comment]
Anyone solved this problem? I'm having it and cannot find any solution

**Comment by roeeba** [comment]
Hi @NickNish09 Can you please share the code responsible for the upload along with the upload source so we can investigate further?

**Comment by gizipp** [comment]
@roeeba @aleksandar-cloudinary is already https://github.com/cloudinary/cloudinary_gem/blob/master/lib/active_storage/service/cloudinary_service.rb support base64 data URI?

I have same issue `ActiveStorage::IntegrityError (Unsupported source URL: #<StringIO:0x00007fb5cb49d198>):` when tying upload base64 data uri using ActiveStorage.

The version I am using :
- Rails 6.0.2.1
- ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
- cloudinary (1.13.2)

The responsible code for uploading is

```ruby
# in my concern
  module Uploader
    def decode_base_64(file_text, filename = Time.current.to_i)
      base64_image  = file_text.sub(/^data:.*,/, '')
      decoded_image = Base64.decode64(base64_image)
      image_io      = StringIO.new(decoded_image)

      return {
        io: image_io,
        filename: filename
      }
    end
  end

# controller
  def update_avatar
    if params[:avatar].present?
      filename = "avatar-#{current_user.id}-#{Time.current.to_i}.png"
      current_user.avatar.attach(decode_base_64(params[:avatar], filename))
    end

    json_response(current_profile)
  end
```

The curl uploaded base64 file is here
https://gist.github.com/gizipp/80d7a0b7eabed0e6f03ba5eadb84d1f5

It working well on`:local` storage config but got an error when using `:cloudinary`.

**Comment by gizipp** [comment]
> Anyone solved this problem? I'm having it and cannot find any solution

I forked and monkey patch it. Not sure it was a proper solution but at least it works me. Basically, I handle StringIO as file. 

https://github.com/gizipp/cloudinary_gem/commit/928bd784ae5085e46cc53ccffdd457eb992e8c16


```ruby
#lib/active_storage/service/cloudinary_service.rb:31
io = handle_string_io_as_file(io, filename)

private
def handle_string_io_as_file(io, filename)
  return io unless io.class == StringIO

  file = Tempfile.new(["temp",".png"], encoding: 'ascii-8bit')
  file.binmode
  file.write io.read
  file.open
end
```

**Comment by hugoh59** [comment]
Any fix on the public version soon?

**Comment by hugoh59** [comment]
Could you share more information as to where you pasted this code in the file? @gizipp thanks

**Comment by const-cloudinary** [comment]
Fixed in 1.16.0

**Comment by cwebster85** [comment]
Hello, I'm getting errors loading a rails app due to cloudinary, not sure if anyone can offer some advice？

Here are the errors:

ActiveStorage::IntegrityError: Invalid Signature 4424225d948a8cafd2feac88d8f6a54ca8800bed. String to sign - 'context=active_storage_key=fyo3dskscjxmxa6b28dhena57pbe|checksum=XwDKZoGzuYOQlA4l7CKk/w\=\=&public_id=fyo3dskscjxmxa6b28dhena57pbe&timestamp=1677082135'.

Caused by:
CloudinaryException: Invalid Signature 4424225d948a8cafd2feac88d8f6a54ca8800bed. String to sign - 'context=active_storage_key=fyo3dskscjxmxa6b28dhena57pbe|checksum=XwDKZoGzuYOQlA4l7CKk/w\=\=&public_id=fyo3dskscjxmxa6b28dhena57pbe&timestamp=1677082135'.

**Comment by wissam-khalili** [comment]
Hi there,

I would suggest upgrading your Cloudinary Ruby SDK to the latest version - 1.25 and giving it a second try.
Please let me know how it goes.

Regards,
Wissam

**Comment by cwebster85** [comment]
Hi Wissam,

Many thanks for your reply.

I updated it but I'm still getting the same error as follows:

rails aborted!
ActiveStorage::IntegrityError: Invalid Signature
e01a12e16c47a38e6c904b3c9872f3d8a922b5d9. String to sign -
'context=active_storage_key=p9h3low1xsd75o6zvvhcy8uwc6ew|checksum=XwDKZoGzuYOQlA4l7CKk/w\=\=&public_id=p9h3low1xsd75o6zvvhcy8uwc6ew&timestamp=1677170098'.
/Users/chriswebster1985/daytrippers/db/seeds.rb:270:in `<main>'
/Users/chriswebster1985/daytrippers/bin/rails:9:in `<top (required)>'
/Users/chriswebster1985/daytrippers/bin/spring:15:in `<top (required)>'

Caused by:
CloudinaryException: Invalid Signature
e01a12e16c47a38e6c904b3c9872f3d8a922b5d9. String to sign -
'context=active_storage_key=p9h3low1xsd75o6zvvhcy8uwc6ew|checksum=XwDKZoGzuYOQlA4l7CKk/w\=\=&public_id=p9h3low1xsd75o6zvvhcy8uwc6ew&timestamp=1677170098'.
/Users/chriswebster1985/daytrippers/db/seeds.rb:270:in `<main>'
/Users/chriswebster1985/daytrippers/bin/rails:9:in `<top (required)>'
/Users/chriswebster1985/daytrippers/bin/spring:15:in `<top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

**Comment by aleksandar-cloudinary** [comment]
Hi @cwebster85, Thanks for your response. I checked your cloud's logs and all requests have actually been failing (also `destroys()`) due to an invalid signature. Therefore, as a first step, we need to verify if the right API credentials are included in your app's configuration. To do that, may I please ask you to submit a ticket to us via: https://support.cloudinary.com/hc/requests/new and share with us how you've configured the API Key/Secret and Cloud name in your app? This ticket you'll create with our support team will be private, unlike this thread. Please don't include the full API credentials (API Secret) in your message that you'll share as part of the ticket, but you could include the first and last 4 characters of the API Secret. We can use that to verify and double-check it's the correct value for your cloud.

**Comment by cwebster85** [comment]
Yes right away!

Thank you so much for your timely responses!

**Comment by aleksandar-cloudinary** [comment]
Thank you!
